{
 "title": "Kafka Heartbeat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "B1-ms",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '1') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "B2-ms",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '2') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "B3-ms",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '3') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "B4-ms",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '4') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "B5-ms",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '5') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "5" }
     ]
    }
   ]
  },
  {
   "title": "B6-ms",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '6') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "6" }
     ]
    }
   ]
  },
  {
   "title": "B1-heartbeats",
   "type": "stat",
   "description": "#Heartbeats",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT COUNT(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '1') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "B2-heartbeats",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT COUNT(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '2') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "B3-heartbeats",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT COUNT(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '3') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "B4-heartbeats",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT COUNT(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '4') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "B5-heartbeats",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT COUNT(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '5') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "5" }
     ]
    }
   ]
  },
  {
   "title": "B6-heartbeats",
   "type": "stat",
   "description": "Produce ms to Broker-1",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT COUNT(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '6') AND (\"value\"  > 0  ) AND time > now() - 5m GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "6" }
     ]
    }
   ]
  },
  {
   "title": "Broker Produce Latency (ms)",
   "type": "timeseries",
   "description": "Milliseconds to produce one message to brokers 1,2,3,4.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "B1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '1') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "B2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '2') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "B3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '3') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "B4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '4') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "B5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '5') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "B6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "heartbeat",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"heartbeat\" WHERE (\"broker\" = '6') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "broker", "operator": "=", "value": "6" }
     ]
    }
   ]
  }
 ]
}